version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  back-tier:

services:
  immudb:
    build:
      context: ./
    ports:
      - "3322:3322"
      - "9497:9497"
    networks:
      - back-tier

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - back-tier

  immudb-f1:
    depends_on:
      - immudb
    build:
      context: ./immudb-f1/
    networks:
      - back-tier
